### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo_tec#1]
[REPORTE_ENTREVISTA_Daisy_Adriana_Maribel.pdf](https://github.com/user-attachments/files/16851750/REPORTE_ENTREVISTA_Daisy_Adriana_Maribel.pdf)

**Comment by Nancy-0714** [comment]
Bien hecho, obtuvieron 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
